@startuml
'https://plantuml.com/component-diagram


package "Easy ETL(数据清洗)" {


[Easy ETL(数据清洗)] --> [Sink]

[Easy ETL(数据清洗)] --> [Listener]

node "Sink" {

' elasticsearch sink 组件
node {
[elasticsearch-sink]

database elasticsearch{
folder "elasticsearch-index"{
[elasticsearch-索引]
}
folder "elasticsearch-partition"{
[elasticsearch-分片]
}
}

[Sink] --> [elasticsearch-sink]
[elasticsearch-sink] -> [elasticsearch-索引]
[elasticsearch-索引] --> [elasticsearch-分片]
}




' kafka
node {
[kafka-sink]

database kafka{
folder "kafka-topic"{
[kafka-主题]
}
folder "kafka-partition"{
[kafka-分片]
}
}
[Sink] --> [kafka-sink]
[kafka-sink] -> [kafka-主题]
[kafka-主题]--> [kafka-分片]

}



'mysql
node {
[mysql-sink]
database mysql{
folder "schema"{
[mysql-库]
}
folder "table"{
[mysql-表]
}
}
[Sink] --> [mysql-sink]
[mysql-sink]-->[mysql-库]
[mysql-库]--> [mysql-表]

}



}

node "Listener"{
    [kafka-listener]
    [mysql-listener]
}


}



@enduml


@startuml
'https://plantuml.com/sequence-diagram

autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml