---
apiVersion: v1
data:
  VPN_ADDL_PASSWORDS: pass1 pass2
  VPN_ADDL_USERS: user1 user2
  VPN_DNS_SRV1: 10.100.0.0/16
  VPN_IPSEC_PSK: 6JhixxWU0u9REqATiFrEAG0
  VPN_NETWORK_INTERFACE: eth0
  VPN_PASSWORD: admin
  VPN_PUBLIC_IP: 124.222.48.62
  VPN_USER: admin
kind: ConfigMap
metadata:
  name: ipsec-vpn-server-config
  namespace: normal-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/displayName: ipsec-vpn-server
  labels:
    k8s.kuboard.cn/layer: gateway
    k8s.kuboard.cn/name: ipsec-vpn-server
  name: ipsec-vpn-server
  namespace: normal-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: gateway
      k8s.kuboard.cn/name: ipsec-vpn-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: gateway
        k8s.kuboard.cn/name: ipsec-vpn-server
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: ipsec-vpn-server-config
          image: hwdsl2/ipsec-vpn-server
          imagePullPolicy: IfNotPresent
          name: ipsec-vpn-server
          resources: { }
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /lib/modules
              name: lib
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /lib/modules
            type: Directory
          name: lib

---
apiVersion: v1
kind: Service
metadata:
  annotations: { }
  labels:
    k8s.kuboard.cn/layer: gateway
    k8s.kuboard.cn/name: ipsec-vpn-server
  name: ipsec-vpn-server
  namespace: normal-system
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
    - name: 7te7bj
      nodePort: 500
      port: 500
      protocol: UDP
      targetPort: 500
    - name: ktzjiz
      nodePort: 4500
      port: 4500
      protocol: UDP
      targetPort: 4500
  selector:
    k8s.kuboard.cn/layer: gateway
    k8s.kuboard.cn/name: ipsec-vpn-server
  sessionAffinity: None
  type: NodePort

