---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: skywalking-oap
  namespace: skywalking
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: skywalking-oap
  annotations: { }
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: skywalking-oap
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: skywalking-oap
    spec:
      containers:
        - name: skywalking-oap
          image: 'apache/skywalking-oap-server:8.9.0'
          envFrom:
            - configMapRef:
                name: skywalking
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: skywalking-rocketbot-ui
  namespace: skywalking
  labels:
    k8s.eip.work/layer: web
    k8s.eip.work/name: skywalking-rocketbot-ui
    k8s.kuboard.cn/name: skywalking-rocketbot-ui
  annotations:
    k8s.eip.work/displayName: skywalking-rocketbot-ui
    k8s.eip.work/ingress: 'false'
    k8s.eip.work/service: NodePort
    k8s.eip.work/workload: skywalking-rocketbot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.eip.work/layer: web
      k8s.eip.work/name: skywalking-rocketbot-ui
  template:
    metadata:
      labels:
        k8s.eip.work/layer: web
        k8s.eip.work/name: skywalking-rocketbot-ui
    spec:
      volumes:
        - name: default-conf
          configMap:
            name: nginx-cnf
            items:
              - key: default-conf
                path: default.conf
            defaultMode: 420
        - name: nginx-conf
          configMap:
            name: nginx-cnf
            items:
              - key: nginx-conf
                path: nginx.conf
            defaultMode: 420
        - name: tz
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: File
      containers:
        - name: nginx
          image: >-
            harbor.yk.bytedad.cn/laihui/skywalking-rocketbot-ui:master_latest
          envFrom:
            - configMapRef:
                name: nginx-cnf
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: 100Mi
          volumeMounts:
            - name: default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: tz
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
  serviceName: skywalking-rocketbot-ui
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10

---
kind: Service
apiVersion: v1
metadata:
  name: skywalking-oap
  namespace: skywalking
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: skywalking-oap
spec:
  ports:
    - name: mfjdhi
      protocol: TCP
      port: 11800
      targetPort: 11800
      nodePort: 31429
    - name: 2cfecn
      protocol: TCP
      port: 12800
      targetPort: 12800
      nodePort: 30341
  selector:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: skywalking-oap
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

---
kind: Service
apiVersion: v1
metadata:
  name: skywalking-rocketbot-ui
  namespace: skywalking
  labels:
    k8s.eip.work/layer: web
    k8s.eip.work/name: skywalking-rocketbot-ui
    k8s.kuboard.cn/name: skywalking-rocketbot-ui
  annotations:
    k8s.eip.work/displayName: skywalking-rocketbot-ui
    k8s.eip.work/workload: skywalking-rocketbot-ui
spec:
  ports:
    - name: aswmqa
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30630
  selector:
    k8s.eip.work/layer: web
    k8s.eip.work/name: skywalking-rocketbot-ui
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-cnf
  namespace: skywalking
data:
  default-conf: |-
    server {
      listen       80;
      server_name  localhost;
      client_max_body_size 200M;

      #charset koi8-r;
      #access_log  /var/log/nginx/log/host.access.log  main;
      location ^~/ {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
      #graphql
      location /graphql {
          proxy_pass http://skywalking-oap.skywalking:12800;
          proxy_set_header Host $host:$proxy_port;
      }

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
  nginx-conf: |-
    user  root;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        underscores_in_headers on;

        include /etc/nginx/conf.d/*.conf;
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: skywalking
  namespace: skywalking
data:
  ES_JAVA_OPTS: '-Xms512m -Xmx512m'
  SW_OAP_ADDRESS: 'skywalking-oap:12800'
  TZ: Asia/Shanghai
  bootstrap.memory_lock: 'true'
  discovery.type: single-node

