---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: db
    k8s.kuboard.cn/name: clickhouse-server
  name: clickhouse-server
  namespace: click-house
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: db
      k8s.kuboard.cn/name: clickhouse-server
  serviceName: clickhouse-server
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: db
        k8s.kuboard.cn/name: clickhouse-server
    spec:
      containers:
        - image: yandex/clickhouse-server
          imagePullPolicy: Always
          name: clickhouse-server
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: db
    k8s.kuboard.cn/name: clickhouse-server
  name: clickhouse-server
  namespace: click-house
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - name: ynapyh
      nodePort: 29729
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: y7hn4z
      nodePort: 1391
      port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    k8s.kuboard.cn/layer: db
    k8s.kuboard.cn/name: clickhouse-server
  sessionAffinity: None
  type: NodePort

