---
apiVersion: v1
data:
  ES_JAVA_OPTS: '-Xms512m -Xmx512m'
  SW_OAP_ADDRESS: 'skywalking-oap:12800'
  SW_STORAGE: elasticsearch
  SW_STORAGE_ES_CLUSTER_NODES: 'elasticsearch-7:9200'
  TZ: Asia/Shanghai
  bootstrap.memory_lock: 'true'
  discovery.type: single-node
kind: ConfigMap
metadata:
  name: skywalking
  namespace: skywalking


---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/displayName: skywalking-ui
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: skywalking-ui
  name: skywalking-ui
  namespace: skywalking
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: skywalking-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: skywalking-ui
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: skywalking
          image: 'apache/skywalking-ui:8.9.0'
          imagePullPolicy: IfNotPresent
          name: skywalking-ui
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations: { }
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: skywalking-ui
  name: skywalking-ui
  namespace: skywalking
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - name: z7744h
      nodePort: 30441
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: skywalking-ui
  sessionAffinity: None
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: { }
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: skywalking-oap
  name: skywalking-oap
  namespace: skywalking
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: skywalking-oap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: skywalking-oap
    spec:
      containers:
        - image: 'apache/skywalking-oap-server:8.9.0'
          envFrom:
            - configMapRef:
                name: skywalking
          imagePullPolicy: IfNotPresent
          name: skywalking-oap
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations: { }
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: skywalking-oap
  name: skywalking-oap
  namespace: skywalking
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - name: 28rmcj
      port: 11800
      protocol: TCP
      targetPort: 11800
    - name: wrzjc4
      port: 12800
      protocol: TCP
      targetPort: 12800
  selector:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: skywalking-oap
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    k8s.kuboard.cn/displayName: elasticsearch-7
  labels:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: elasticsearch-7
  name: elasticsearch-7
  namespace: skywalking
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: cloud
      k8s.kuboard.cn/name: elasticsearch-7
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: cloud
        k8s.kuboard.cn/name: elasticsearch-7
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: skywalking
          image: 'elasticsearch:7.10.1'
          imagePullPolicy: IfNotPresent
          name: elasticsearch
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: File
          name: tz
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        annotations:
          k8s.eip.work/pvcType: Dynamic
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: nfs2-storage
        volumeMode: Filesystem

---
apiVersion: v1
kind: Service
metadata:
  annotations: { }
  labels:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: elasticsearch-7
  name: elasticsearch-7
  namespace: skywalking
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - name: anesya
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: qrybhm
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: elasticsearch-7
  sessionAffinity: None
  type: ClusterIP




