@startuml
skinparam rectangle<<behavior>> {
	roundCorner 25
}
sprite $bProcess jar:archimate/business-process
sprite $aService jar:archimate/application-service
sprite $aComponent jar:archimate/application-component

rectangle "LazyOperationProxy"  as Proxy <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethod"  as LazyOperationMethod <<$bProcess>><<behavior>> #Business
rectangle "AbstractLazyOperationMethod"  as AbstractLazyOperationMethod <<$bProcess>><<behavior>> #Business


rectangle "LazyOperationMethodCreate"  as Create <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodExecute" as Execute <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodExecuteOne" as ExecuteOne <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodExecuteSQL" as ExecuteSQL <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodExecuteSQLForBean" as ExecuteSQLForBean <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodInsert"  as Insert <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodPage" as Page <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodPerfect" as Perfect <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodSmartUpsert" as SmartUpsert <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodUpdate" as Update <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodUpsert"  as Upsert <<$bProcess>><<behavior>> #Business
rectangle "LazyOperationMethodUpsertRemoveNull" as UpsertRemoveNull <<$bProcess>><<behavior>> #Business


Proxy *-down- LazyOperationMethod
LazyOperationMethod *-down- AbstractLazyOperationMethod

AbstractLazyOperationMethod *-down- Create
AbstractLazyOperationMethod *-down- Execute
AbstractLazyOperationMethod *-down- ExecuteOne
AbstractLazyOperationMethod *-down- ExecuteSQL
AbstractLazyOperationMethod *-down- ExecuteSQLForBean
AbstractLazyOperationMethod *-down- Insert
AbstractLazyOperationMethod *-down- Page
AbstractLazyOperationMethod *-down- Perfect
AbstractLazyOperationMethod *-down- SmartUpsert
AbstractLazyOperationMethod *-down- Update
AbstractLazyOperationMethod *-down- Upsert
AbstractLazyOperationMethod *-down- UpsertRemoveNull


rectangle "AnalyzePersistenceRepository" as AnalyzePersistenceRepository <<$aService>><<behavior>> #Application


AnalyzePersistenceRepository -up-> Create


rectangle "execute\n执行sql\nSystem" as 执行语句 <<$aComponent>> #Application

执行语句 .up.|> AnalyzePersistenceRepository

legend left
Example from the "Archisurance case study" (OpenGroup).
See
====
<$bProcess> :business process
====
<$aService> : application service
====
<$aComponent> : application component
endlegend
@enduml
