---
version: '2'
services:
  pulsar:
    image: apachepulsar/pulsar-all
    hostname: pulasr
    container_name: pulasr
    ports:
      - "8080:8080"
      - "6650:6650"
    entrypoint: bin/pulsar standalone


  # 管理端访问地址 http://localhost:9527
  pulsar-manager:
    image: apachepulsar/pulsar-manager
    hostname: pulsar-manager
    container_name: pulsar-manager
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties

  ## pulsar-nginx pulsar-manager 配置信息
#  pulsar-nginx:
#    image: nginx
#    hostname: nginx
#    container_name: pulsar-nginx
#    depends_on:
#      - pulsar
#      - pulsar-manager
