spring:
  lazy:
    printf-query: on
    ddl-configure:
      ddl-auto: update
      ddl-perfect-commitment: 我承诺完善表结构，支持表字段删除操作
      extra-fields:
        - name: name
          columnName: column_name
          alias: alias
          columnType: varchar(255)
          comment: 额外字段
          exist: true
      #        - name: id
      #          columnName: id
      #          columnType: bigint
      #          comment: 主键
      #          exist: true
      #          notNull: true
      #          extra: AUTO_INCREMENT
      #          key: true

      schema-script:
#        class-path-resources:
#          - sql/sys_user.sql
#          - sql/address.sql
        file-system-resources:
          - /Users/wujiawei/IdeaProjects/wu-framework-parent/wu-smart-intergration/wu-smart-acw/wu-smart-acw-server/src/main/resources/sql/sys_user.sql
          - /Users/wujiawei/IdeaProjects/wu-framework-parent/wu-smart-intergration/wu-smart-acw/wu-smart-acw-server/src/main/resources/sql/address.sql
      out-put-table-structure: true

    #        url-resources:
    #          - http://192.168.17.221:30570/management-deploy-provider/api/middleground/tenant-sql-173.sql

    authorization:
      verification: session
    enable-reverse-engineering: true
    reverse-engineering:
      reverse-engineering-mvc:
        web-architecture: ddd_architecture
      enable-mybatis: false
      enable-lazy: true
      enable-lombok-data: true
      enable-swagger: true
      enable-lombok-accessors: true
      enable-lazy-crud: false
      enable-normal-crud: true

#      entity-suffix: DO
    enable-auto-schema: on

  easy:
    print-execute-time: on
    print-params: off
  application:
    name: acw-simple



