
spring:
  datasource:
    url: jdbc:mysql://${MAIN_DB_HOST:127.0.0.1:3306}/acw_simple
    username: ${MAIN_DB_USERNAME:root}
    password: ${MAIN_PASSWORD:wujiawei}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: acw-simple



