#====================================Seata Config===============================================
seata:
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: free.seata.yk.bytedad.cn:80
  config:
    type: file
  registry:
    type: file
  enable-auto-data-source-proxy: false

  client:
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
      only-care-update-columns: true
