server:
  port: 18080

spring:
  datasource:
    url: jdbc:h2:./h2-db:acw;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;OLD_INFORMATION_SCHEMA=TRUE;AUTO_SERVER=TRUE;
    username: root
    password: wujiawei
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-admin-password: wujiawei
        web-allow-others: true
        trace: true
  lazy:
    printf-query: on
    ddl-configure:
      ddl-auto: perfect
    #      extra-fields:
    #        - name : name
    #          columnName: column_name
    #          alias: alias
    #          columnType: varchar(255)
    #          comment: 额外字段
    #          exist: true

    authorization:
      verification: session
    enable-reverse-engineering: true
    reverse-engineering:
      reverse-engineering-mvc:
        enable-lazy-operation-mvc: true
      enable-mybatis: false
      enable-lazy: true
      enable-lombok-data: true
      enable-swagger: true
      enable-lombok-accessors: true
      entity-suffix: Uo
  easy:
    print-execute-time: on
  application:
    name: acw-server



