spring:
  lazy:
    netty:
      inet-host: 127.0.0.1
      inet-port: 19080
      #      inet-path: middleground-on-cloud-heartbeat-server
#      inet-getHost: 124.222.48.62 # 服务端地址
#      inet-getPort: 30676 #服务端端口
      inet-path: middleground-on-cloud-heartbeat-server
      client-id: acw-server # 客户端ID

