server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://${MAIN_DB_HOST:127.0.0.1:3306}/acw?allowMultiQueries=true&useUnicode=true&autoReconnect=true&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&databaseTerm=SCHEMA
    username: ${MAIN_DB_USERNAME:root}
    password: ${MAIN_PASSWORD:wujiawei}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
  application:
    name: acw-server



