spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2-db:acw;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: root
    password: wujiawei
    type: org.h2.jdbcx.JdbcDataSource
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: true
        web-admin-password: wujiawei

#  spring.datasource.driverClassName=org.h2.Driver
#  #连接信息数据库文件保存位置（嵌入式）
#  #~表示当前用户目录C:\Users\Administrator
#  #spring.datasource.url=jdbc:h2:~/test;MODE=MYSQL
#  spring.datasource.url=jdbc:h2:E:/h3/test;MODE=MYSQL
#  #spring.datasource.url=jdbc:h2:file:./dbconfig/test;MODE=MYSQL
#  spring.datasource.username=root
#  spring.datasource.password=root
#  #是否开启控制台
#  spring.h2.console.enabled=true
#  #控制台路径
#  spring.h2.console.path=/h2