https:
  authorization:
    password: gps@zdzk
    platform-name: 测试https接口
    username: gps_zdzk
server:
  port: 2018

spring:
  profiles:
    active: wjw
  wu:
    shiro:
      verification: session
  hbase:
    zookeeperQuorum: 'k8s.wu2020.top:2181'
  redis:
    host: k8s.wu2020.top


wu:
  database:
    mapper:
      scan-xml-path: classpath*:wu-mapper/*Dao.xml

#debug: true
mybatis:
  mapperLocations: classpath:mapper/**/*.xml


easy:
  upsert:
    config:
      batch-limit: 10000


