https:
  authorization:
    password: gps@zdzk
    platform-name: 测试https接口
    username: gps_zdzk
server:
  port: 2018

spring:
  profiles:
    active: wjw
  wu:
    authorization:
      verification: session
      un-check-api-path:
        "/public/**"
    http:
      http-proxy-type: fixed
      proxy: 192.168.1.22
      port: 50
  hbase:
#    zookeeperQuorum: 'k8s.wu-framework.com:2181'
#  redis:
#    host: k8s.wu-framework.com


  easy:
    upsert:
      config:
        batch-limit: 10000





