spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useUnicode=true&autoReconnect=true&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: wujiawei
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    ignore-exported-fields:
    #      - id
    special-fields:
      - ASC
    enable-binlog: true
    type: com.mysql.cj.jdbc.MysqlDataSource
  lazy:
    enable-reverse-engineering: false
    reverse-engineering:
      enable-lazy: false
      enable-my-batis: true
      orm-architecture: lazy
      web-architecture: ddd_architecture
    enable-auto-schema: true
