https:
  authorization:
    password: gps@zdzk
    platform-name: 测试https接口
    username: gps_zdzk
server:
  port: 2018

spring:
  profiles:
    active: empty
  wu:
    shiro:
      verification: session
  hbase:
#    zookeeperQuorum: 'k8s.wu-framework.com:2181'
  redis:
    host: k8s.wu-framework.com


easy:
  upsert:
    config:
      batch-limit: 10000


