spring:
  datasource:
    url: jdbc:mysql://192.168.17.222:31712/etms_2_0_central_terminal?allowMultiQueries=true&useUnicode=true&autoReconnect=true&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
