spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/etms_2_0_central_terminal11?allowMultiQueries=true&useUnicode=true&autoReconnect=true&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wujiawei
    driver-class-name: com.mysql.cj.jdbc.Driver
  lazy:
    enable-auto-schema: true
